Fred refactor
ClubCloudTech/myvideoroom-wordpress-plugin pull request #11
Opened 2021-05-17 16:58 UTC by ccfredbaum

2021-05-17 17:01 UTC, alecsammon commented on my-video-room/core/class-sitedefaults.php
> +use \MyVideoRoomExtrasPlugin\Modules\WooCommerceBookings\WCHelpers;
Not sure about this one!

2021-05-17 17:06 UTC, ccfredbaum commented on my-video-room/core/class-sitedefaults.php
> +use \MyVideoRoomExtrasPlugin\Modules\WooCommerceBookings\WCHelpers;
I will fix

2021-05-17 17:25 UTC, ccfredbaum commented on my-video-room/core/class-sitedefaults.php
> +use \MyVideoRoomExtrasPlugin\Modules\WooCommerceBookings\WCHelpers;
fixed

2021-05-17 19:34 UTC, alecsammon requested changes
Initial pass - hopefully comments are helpful

2021-05-17 19:34 UTC, alecsammon commented on my-video-room/core/shortcode/class-uservideopreference.php
> +	private static int $id_index = 0;
I have a new and better way of doing this now. 

In the view you can call `$html_lib = Factory::get_instance( HTML::class, array( $name ) );`
and then use
`id="<?php echo \esc_attr( $html_lib->get_id( '....' ) ); ?>"`

This means that this file doesn't need to keep track of ids.

2021-05-17 19:34 UTC, alecsammon commented on my-video-room/core/shortcode/class-uservideopreference.php
> +			sanitize_text_field( wp_unslash( $_POST['myvideoroom_extras_user_room_name'] ?? null ) ) === $room_name
You can now do this:

```
$post_library = Factory::get_instance( HttpPost::class );
if ( $post_library->is_admin_post_request() && $post_library->get_text_parameter('extras_user_room_name') === $room_name) {
```

2021-05-17 19:34 UTC, alecsammon commented on my-video-room/core/shortcode/class-uservideopreference.php
> +			sanitize_text_field( wp_unslash( $_POST['myvideoroom_extras_user_room_name'] ?? null ) ) === $room_name
also a usage of the word `extras` here.

2021-05-17 19:34 UTC, alecsammon commented on my-video-room/core/shortcode/class-uservideopreference.php
> +			$layout_id               = sanitize_text_field( wp_unslash( $_POST['myvideoroom_extras_user_layout_id_preference'] ?? null ) );
You can now use:
`$layout_id = $post_library->get_text_parameter( 'user_layout_id_preference' )`;

2021-05-17 19:34 UTC, alecsammon commented on my-video-room/core/shortcode/class-uservideopreference.php
> +			isset( $_SERVER['REQUEST_METHOD'] ) &&
we need to find a better way of doing this.

2021-05-17 19:34 UTC, alecsammon commented on my-video-room/core/shortcode/class-uservideopreference.php
> +	public function get_available_layouts( array $allowed_tags = array( 'basic' ) ): array {
this functionality is available from `MyVideoRoomPlugin\Library\AvailableScenes` now.

2021-05-17 19:34 UTC, alecsammon commented on my-video-room/core/views/header/header.php
> +	wp_enqueue_script( 'myvideoroom-admin-tabs' );
I don't think we should be enqueuing scripts in the views. This should happen in the initialiser methods.

2021-05-17 19:34 UTC, alecsammon commented on my-video-room/core/views/header/view-roomheader.php
> +	if ( isset( $_SERVER['REQUEST_METHOD'] )
this doesn't feel like view logic

2021-05-17 19:34 UTC, alecsammon commented on my-video-room/core/views/header/header.php
> +return function (
ideally we should have a comment explaining the parameters of this function. I think phpcs has a bug where it doesn't show a warning here.

2021-05-17 19:34 UTC, alecsammon commented on my-video-room/core/views/header/view-roomheader.php
> + * @param string|null $current_user_setting
I think this comment is in the wrong place (and is wrong!)

2021-05-17 19:34 UTC, alecsammon commented on my-video-room/core/views/header/view-roomheader.php
> +	if ( $meeting_link ) {
again I'm not sure if this is view logic.

2021-05-17 19:34 UTC, alecsammon commented on my-video-room/core/views/header/view-roomheader.php
> +				echo '<input type="submit" name="submit" id="submit" class="button mvr-form-button mvr-form-button-max" value="Exit Meeting"  />';
missing transalation

2021-05-17 19:34 UTC, alecsammon commented on my-video-room/core/views/view-settings-core.php
> +/**
I think this comment should be moved down to the function.

2021-05-17 19:34 UTC, alecsammon commented on my-video-room/core/views/view-settings-core.php
> +use MyVideoRoomPlugin\Core\DAO\ModuleConfig;
feels wrong that a view knows about a DAO

2021-05-17 19:34 UTC, alecsammon commented on my-video-room/core/views/view-settings-core.php
> +		array( 'basic', 'premium' )
the last parameter of tags `array( 'basic', 'premium' )` is now deprecated and not used.

2021-05-17 19:34 UTC, alecsammon commented on my-video-room/css/mvr-admin-bar.css
> +    display: none!important;
we should try and avoid using `!important` if possible.

2021-05-17 19:34 UTC, alecsammon commented on my-video-room/css/mvr-admin-bar.css
> +}
missing new line at end of file. You should be able to setup vscode to always ensure these are here.

2021-05-17 19:34 UTC, alecsammon commented on my-video-room/css/mvr-menutab.css
> +	font-family: "Montserrat", Sans-serif;
I'm not sure about overriding the themes font.

2021-05-17 19:34 UTC, alecsammon commented on my-video-room/js/mvr-frame-refresh.js
> +/**
this would be better wrapped in a function that can be called - instead of just when the file is loaded.

```
function myvideoroom_reload_page() {
    window.top.location.reload();
}
```

2021-05-17 19:34 UTC, alecsammon commented on my-video-room/js/outer-tabbed.js
> +jQuery.noConflict()(
so I have a better way of loading these files now:

```
(function ( $ ) {
...
)( jQuery );
```

so we can remove the 
`var $ = jQuery.noConflict();` line

2021-05-17 19:34 UTC, alecsammon commented on my-video-room/js/protect-input.js
> +function chText()
this needs to be namespaced - such as `myvideoroom_ch_text`

2021-05-17 19:34 UTC, alecsammon commented on my-video-room/library/class-dependencies.php
> +	const MODULE_BUDDYPRESS_ID       = 434;
not quite sure what these magic numbers represent.

2021-05-17 19:34 UTC, alecsammon commented on my-video-room/library/class-dependencies.php
> +		if ( is_plugin_active( 'buddypress/bp-loader.php' ) ) {
`return ( is_plugin_active( 'buddypress/bp-loader.php' ) );`

2021-05-17 19:34 UTC, alecsammon commented on my-video-room/library/class-meetingidgenerator.php
> +				return 'Invalid Username or Email entered<br>';
not translated

2021-05-17 19:34 UTC, alecsammon commented on my-video-room/library/class-shortcodedocuments.php
> +		?>
can this go in a view?

2021-05-17 19:34 UTC, alecsammon commented on my-video-room/library/class-shortcodedocuments.php
> +				<th style="width:25%; text-align: left;"><h2>[ccsitedefaultconfig]</h2></th>
I think this shortcode is wrong - maybe should be using the constants?

2021-05-17 19:34 UTC, alecsammon commented on my-video-room/library/class-shortcodedocuments.php
> +	<h2>General Shortcodes</h2>
not translated - and throughout.

2021-05-17 19:34 UTC, alecsammon commented on my-video-room/library/class-shortcodedocuments.php
> +	public function render_general_shortcode_docs() {
we can move this into the existing shortcode_reference page - we can maybe look at this together.

2021-05-17 19:34 UTC, alecsammon commented on my-video-room/library/class-templateicons.php
> +		$reception_enabled          = Factory::get_instance( UserVideoPreferenceDAO::class )->read_user_video_settings( $user_id, $room_name, 'reception_enabled' );
I'm worried about the performance of this - can we set this up in way that allows for these all to be fetched with a single database call?

2021-05-17 19:34 UTC, alecsammon commented on my-video-room/library/class-templateicons.php
> +			$icon_output .= '<i class="card dashicons mvr-icons dashicons-lock" title="Your Guests will see the Reception Template of your choice and will not be admitted into the room until you drag their ic
missing translation

2021-05-17 19:34 UTC, alecsammon commented on my-video-room/library/class-userroles.php
> +	 * @return array of roles
the `@return` should be after the `@param`.

2021-05-17 19:34 UTC, alecsammon commented on my-video-room/module/security/class-security.php
> +		return 'Powered by MyVideoRoom';
missing translation

2021-05-17 19:34 UTC, alecsammon commented on my-video-room/module/security/index.php
> +			'Advanced Room Permissions',
missing translation

2021-05-17 19:34 UTC, alecsammon commented on my-video-room/module/security/library/class-pagefilters.php
> +<?php
It would be good to think about this file a bit more. I think it's a bit big, and has too many responsiblities.

2021-05-17 19:34 UTC, alecsammon commented on my-video-room/module/security/library/class-securityengine.php
> +		if ( Factory::get_instance( Dependencies::class )->is_buddypress_active() ) { // Apply to Groups Only.
might be good to see if we can move this into an action or filter - and then have it as part of the buddypress module - to stop the need to have buddypress code throughout the main code base.

2021-05-17 19:34 UTC, alecsammon commented on my-video-room/module/security/shortcode/class-securityvideopreference.php
> +		if ( Factory::get_instance( Dependencies::class )->is_buddypress_active() ) {
this should maybe be via an action or filter.

2021-05-17 19:34 UTC, alecsammon commented on my-video-room/module/security/shortcode/class-securityvideopreference.php
> +			$room_disabled              = sanitize_text_field( wp_unslash( $_POST['myvideoroom_extras_security_room_disabled_preference'] ?? '' ) ) === 'on';
see `get_text_parameter` and  `get_checkbox_parameter` in `MyVideoRoomPlugin\Library\HttpPost`

2021-05-17 19:34 UTC, alecsammon commented on my-video-room/module/security/templates/class-securitybuttons.php
> +		if ( $site_override ) {
missing translations in this block

2021-05-17 19:34 UTC, alecsammon commented on my-video-room/module/security/templates/class-securitybuttons.php
> +			if ( 'nourl' === $input_type ) {
nested loops can become hard to read, and lead to bugs - might be worth thinking about if there is another way we can structure this.

2021-05-17 19:34 UTC, alecsammon commented on my-video-room/module/security/templates/class-securitytemplates.php
> +		?>
can we move the views into view files?

2021-05-17 19:34 UTC, alecsammon commented on my-video-room/module/security/templates/class-securitytemplates.php
> +			echo '<b>' . esc_html( ucfirst( $first_name ) ) . '</b>';
we should use `<strong>` instead of `<b>`

2021-05-17 19:34 UTC, alecsammon commented on my-video-room/module/security/templates/class-securitytemplates.php
> +			' or the group moderators have allowed. Please contact any of the group admins or moderators for assistance. ',
this needs paramatised with `printf`

2021-05-17 19:37 UTC, alecsammon requested changes

2021-05-17 19:37 UTC, alecsammon commented on my-video-room/core/dao/class-moduleconfig.php
> +		if ( ! $post_object ) {
really not a fan of returning magic strings - would be great if this could return just a boolean - if not then a constant would be better.

2021-05-17 19:39 UTC, alecsammon requested changes

2021-05-17 19:39 UTC, alecsammon commented on my-video-room/core/dao/class-moduleconfig.php
> +			$output_link  = '<div style= "display: flex; justify-content: space-between; width: 50%;"> <a href="' . $current_url . '" class="button button-primary" style="background-color:red;" >Disabled</a><
missing translations

2021-05-17 19:39 UTC, alecsammon commented on my-video-room/core/dao/class-moduleconfig.php
> +			<a href="' . $current_url . $sub_tab_tag . '" class="button button-primary" >Enable Module</a>
missing translations

2021-05-17 19:50 UTC, alecsammon commented on my-video-room/module/sitevideo/class-mvrsitevideo.php
> +		$this->add_shortcode( 'sitevideoroom', array( MVRSiteVideoControllers::class, 'sitevideo_shortcode' ) );
this doesn't really work like this - as you have passed a classname and not an object instance to this then it's doing

`MVRSiteVideoControllers::sitevideo_shortcode` instead of `(new MVRSiteVideoControllers())->sitevideo_shortcode()`.

This results in the error ```
Deprecated: Non-static method MyVideoRoomPlugin\Module\SiteVideo\Library\MVRSiteVideoControllers::sitevideo_shortcode() should not be called statically in /var/www/html/wp-content/plugins/my-video-room/class-shortcode.php on line 51
```

instead you probably want to 
```
$site_video_controller = Factory::get_instance( MVRSiteVideoControllers::class );
$this->add_shortcode( 'sitevideoroom', array( site_video_controller, 'sitevideo_shortcode' ) );

```

2021-05-17 19:52 UTC, alecsammon requested changes

2021-05-17 19:52 UTC, alecsammon commented on my-video-room/setup/class-setup.php
> +	public static function install_module_config_table() {
This function does not seam to be called by the setup. This means the the plugin has critical errors as it cannot find the table.

2021-05-17 19:57 UTC, alecsammon commented on my-video-room/core/dao/class-moduleconfig.php
> +		$prepared_query = $wpdb->prepare( $raw_sql );
I think this error is related to here:
```
Notice: wpdb::prepare was called incorrectly. The query argument of wpdb::prepare() must have a placeholder. Please see Debugging in WordPress for more information. (This message was added in version 3.9.0.) in /var/www/html/wp-includes/functions.php on line 5313
```

I guess that you don't need to prepare this statement as there are no parameters.

2021-05-17 20:04 UTC, alecsammon commented on my-video-room/core/views/view-settings-core.php
> +	if ( ! Factory::get_instance( RoomAdmin::class )->check_default_settings_exist() ) {
I don't think this logic should be in the view.

2021-05-17 20:15 UTC, alecsammon commented on my-video-room/core/dao/class-moduleconfig.php
> +		$row = $wpdb->get_row( $prepared_query );
if the table doesn't exist then this throws an error. 

This seams to work:
```
		try {
			// phpcs:ignore WordPress.DB.DirectDatabaseQuery.DirectQuery, WordPress.DB.PreparedSQL.NotPrepared
			$row = $wpdb->get_row( $prepared_query );
			if ( $row ) {
				return true;
			}

			return false;
		} catch (\Throwable $e) {
			return false;
		}
```

2021-05-17 20:16 UTC, alecsammon commented on my-video-room/core/class-sitedefaults.php
> +		add_action( 'mvr_module_submenu_add', array( self::class, 'core_menu_button' ) );
This should be 
```
add_action( 'mvr_module_submenu_add', array( $this, 'core_menu_button' ) );
```

2021-05-17 20:17 UTC, alecsammon commented on my-video-room/module/sitevideo/class-mvrsitevideo.php
> +		add_action( 'mvr_module_submenu_add', array( self::class, 'site_videoroom_menu_button' ) );
this should be:
```
add_action( 'mvr_module_submenu_add', array( $this, 'site_videoroom_menu_button' ) );
```

2021-05-17 20:18 UTC, alecsammon commented on my-video-room/core/dao/class-moduleconfig.php
> +		if ( $module_id_by_url ) {
this variable may be unset

2021-05-18 07:01 UTC, alecsammon commented on my-video-room/library/class-menuhelpers.php
> +	public function remove_admin_bar() {
I don't think this method is used anywhere.

2021-05-18 07:02 UTC, alecsammon commented on my-video-room/library/class-sectiontemplates.php
> +				echo '<a class="nav-tab-active mvr-menu-header-item mvr-main-shortcode" href="#page1' . esc_textarea( $header_length ) . '" >' . esc_html__( 'Video Room', 'my-video-room' ) . '</a>';
I think this should be `esc_attr` instead of `esc_textarea`

2021-05-18 07:02 UTC, alecsammon commented on my-video-room/library/class-sectiontemplates.php
> +			//phpcs:ignore --WordPress.Security.EscapeOutput.OutputNotEscaped - Shortcode Already Escaped.
this `phpcs:ignore` doesn't do anything - looks to be copy/paste

2021-05-18 07:03 UTC, alecsammon commented on my-video-room/library/class-sectiontemplates.php
> +		wp_enqueue_script( 'myvideoroom-admin-tabs' );
I don't think we should enqueue scripts and styles in views

2021-05-18 07:03 UTC, alecsammon commented on my-video-room/library/class-sectiontemplates.php
> +				$output .= '<article id="page2' . $header_length . '" style>';
id need to be unique on a page - so would be good to prefix these with `myvideoroom_`

2021-05-18 07:04 UTC, alecsammon commented on my-video-room/library/class-sectiontemplates.php
> +				$output .= '<article id="page2' . $header_length . '" style>';
Also not sure why the `style>` is here.

2021-05-18 07:05 UTC, alecsammon commented on my-video-room/setup/class-moduledefinition.php
> +class ModuleDefinition extends SiteDefaults {
I don't think this is used anywhere

2021-05-18 07:07 UTC, alecsammon commented on my-video-room/setup/class-roomadmin.php
> +namespace MyVideoRoomPlugin\Setup;
I'm not sure about the namespace here - I'm not sure if this is a `setup` class - or maybe I have misunderstood what setup means

2021-05-18 07:08 UTC, alecsammon commented on my-video-room/setup/class-setup.php
> +						`status_feature1` VARCHAR(255) NULL,
I'm not a fan of these "in case we need it" columns.

2021-05-18 07:09 UTC, alecsammon commented on my-video-room/views/shortcode/view-shortcode-uservideopreference.php
> +					$output .= '<p class="mvr-main-button-enabled" title="Your Guests will see the Reception Template of your choice and will not be admitted into the room until you drag their icon in.">Reception E
missing translation

2021-05-18 07:09 UTC, alecsammon commented on my-video-room/views/shortcode/view-shortcode-uservideopreference.php
> +				$reception_enabled = Factory::get_instance( UserVideoPreferenceDAO::class )->read_user_video_settings( $user_id, $room_name, 'reception_enabled' );
I don't think that views should call the DAO directly, instead it would be better to have the controller do this, and then pass the values to the view.

2021-05-18 07:10 UTC, alecsammon commented on my-video-room/views/shortcode/view-shortcode-uservideopreference.php
> +					<input name="myvideoroom_extras_user_room_name" type="hidden" value="<?php echo esc_attr( $room_name ); ?>" />
references to `extras` throughout this file.

2021-05-18 07:14 UTC, alecsammon commented on my-video-room/module/security/entity/class-securityvideopreference.php
> +	 * Room_name
the `@var`s throughout this file have the wrong type. i.e. this one should be `string` and not `int`.

2021-05-18 07:15 UTC, alecsammon commented on my-video-room/module/security/entity/class-securityvideopreference.php
> +	public function set_allowed_roles( string $allowed_roles = null ): SecurityVideoPreference {
I think that this should receive an array, and the dao should be responsible for converting to a string. It's the database limitation that prevents us storing arrays - and therefor the conversion should happen at that layer

2021-05-18 07:46 UTC, ccfredbaum commented on my-video-room/setup/class-setup.php
> +	public static function install_module_config_table() {
Fixed - this was a weird sync issue.

2021-05-18 07:49 UTC, ccfredbaum commented on my-video-room/library/class-menuhelpers.php
> +	public function remove_admin_bar() {
removed

2021-05-18 07:50 UTC, ccfredbaum commented on my-video-room/library/class-sectiontemplates.php
> +			//phpcs:ignore --WordPress.Security.EscapeOutput.OutputNotEscaped - Shortcode Already Escaped.
yup- removed

2021-05-18 07:51 UTC, ccfredbaum commented on my-video-room/library/class-sectiontemplates.php
> +		wp_enqueue_script( 'myvideoroom-admin-tabs' );
So does this move to the function that calls the view ?

2021-05-18 07:54 UTC, ccfredbaum commented on my-video-room/library/class-sectiontemplates.php
> +				$output .= '<article id="page2' . $header_length . '" style>';
Resolved

2021-05-18 07:56 UTC, ccfredbaum commented on my-video-room/setup/class-moduledefinition.php
> +class ModuleDefinition extends SiteDefaults {
No - I added a function to make it easier to add new modules to DB later on. But its not yet used. Meant to be used by other people adding stuff.

2021-05-18 07:58 UTC, ccfredbaum commented on my-video-room/setup/class-setup.php
> +						`status_feature1` VARCHAR(255) NULL,
OK- removed for all tables.

2021-05-18 08:03 UTC, ccfredbaum commented on my-video-room/module/security/entity/class-securityvideopreference.php
> +	 * Room_name
fixed

2021-05-18 08:10 UTC, alecsammon commented on my-video-room/library/class-sectiontemplates.php
> +		wp_enqueue_script( 'myvideoroom-admin-tabs' );
Yeah - or to the init function

2021-05-18 08:16 UTC, ccfredbaum commented on my-video-room/views/shortcode/view-shortcode-uservideopreference.php
> +					$output .= '<p class="mvr-main-button-enabled" title="Your Guests will see the Reception Template of your choice and will not be admitted into the room until you drag their icon in.">Reception E
Added

2021-05-18 08:23 UTC, ccfredbaum commented on my-video-room/setup/class-roomadmin.php
> +namespace MyVideoRoomPlugin\Setup;
agreed - moved to \DAO

2021-05-18 08:24 UTC, ccfredbaum commented on my-video-room/views/shortcode/view-shortcode-uservideopreference.php
> +					<input name="myvideoroom_extras_user_room_name" type="hidden" value="<?php echo esc_attr( $room_name ); ?>" />
myvideoroom_extras_ now removed across all files replaced with myvideoroom_

2021-05-18 09:37 UTC, ccfredbaum commented on my-video-room/core/class-sitedefaults.php
> +		add_action( 'mvr_module_submenu_add', array( self::class, 'core_menu_button' ) );
updated

2021-05-18 09:39 UTC, ccfredbaum commented on my-video-room/module/sitevideo/class-mvrsitevideo.php
> +		add_action( 'mvr_module_submenu_add', array( self::class, 'site_videoroom_menu_button' ) );
Fixed

2021-05-18 09:41 UTC, ccfredbaum commented on my-video-room/library/class-sectiontemplates.php
> +				echo '<a class="nav-tab-active mvr-menu-header-item mvr-main-shortcode" href="#page1' . esc_textarea( $header_length ) . '" >' . esc_html__( 'Video Room', 'my-video-room' ) . '</a>';
Done- but what is the most elegant escape for just simple text ?

2021-05-18 09:43 UTC, ccfredbaum commented on my-video-room/library/class-sectiontemplates.php
> +		wp_enqueue_script( 'myvideoroom-admin-tabs' );
I register all scripts in the init function - but usually only enqueue on pages that I need them on. So I will test to see if the function that calls the views can hold the enqueue.

2021-05-18 09:48 UTC, ccfredbaum commented on my-video-room/setup/class-moduledefinition.php
> +class ModuleDefinition extends SiteDefaults {
deleted

2021-05-18 09:58 UTC, ccfredbaum commented on my-video-room/core/views/view-settings-core.php
> +	if ( ! Factory::get_instance( RoomAdmin::class )->check_default_settings_exist() ) {
moved

2021-05-18 10:11 UTC, alecsammon commented on my-video-room/library/class-sectiontemplates.php
> +		wp_enqueue_script( 'myvideoroom-admin-tabs' );
this is where my WordPress knowledge is a bit limited - not sure about the best place to ensure scripts and styles are loaded correctly. 

Will do some more reading.

2021-05-18 10:36 UTC, ccfredbaum commented on my-video-room/core/dao/class-moduleconfig.php
> +		$row = $wpdb->get_row( $prepared_query );
updated

2021-05-18 10:39 UTC, ccfredbaum commented on my-video-room/core/dao/class-moduleconfig.php
> +		if ( $module_id_by_url ) {
please explain ?

2021-05-18 10:39 UTC, alecsammon commented on my-video-room/library/class-sectiontemplates.php
> +		wp_enqueue_script( 'myvideoroom-admin-tabs' );
I guess that this is the line that matters:
```
The function should be called using the wp_enqueue_scripts action hook if you want to call it on the front-end of the site, like in the examples above. To call it on the administration screens, use the admin_enqueue_scripts action hook. For the login screen, use the login_enqueue_scripts action hook. Calling it outside of an action hook can lead to problems, see the ticket #11526 for details.
```
https://developer.wordpress.org/reference/functions/wp_enqueue_script/#notes

2021-05-18 10:42 UTC, ccfredbaum commented on my-video-room/class-activation.php
> +		Factory::get_instance( SiteDefaults::class )->initialise_module();
agreed- changed

2021-05-18 10:46 UTC, alecsammon commented on my-video-room/core/dao/class-moduleconfig.php
> +		if ( $module_id_by_url ) {
sorry - wasn't clear.

The variable `$module_id_by_url` is created in an `if` statement above.

As such with some paths through the code the variable `$module_id_by_url` may never be defined. This will lead to a PHP notice.

Either set `$module_id_by_url = null;` at the top of the function (I would recommend) - or - change your `if` condition to be `if ( isset( $module_id_by_url ) && $module_id_by_url )`.

2021-05-18 11:26 UTC, ccfredbaum commented on my-video-room/module/security/templates/class-securitytemplates.php
> +			echo '<b>' . esc_html( ucfirst( $first_name ) ) . '</b>';
Done

2021-05-18 11:33 UTC, ccfredbaum commented on my-video-room/core/dao/class-moduleconfig.php
> +			<a href="' . $current_url . $sub_tab_tag . '" class="button button-primary" >Enable Module</a>
Done

2021-05-18 11:37 UTC, ccfredbaum commented on my-video-room/core/dao/class-moduleconfig.php
> +			$output_link  = '<div style= "display: flex; justify-content: space-between; width: 50%;"> <a href="' . $current_url . '" class="button button-primary" style="background-color:red;" >Disabled</a><
Done

2021-05-18 11:38 UTC, alecsammon commented on my-video-room/css/mvr-menutab.css
> +.nav-tab-active {
this style set is breaking the main tab design

2021-05-18 11:44 UTC, ccfredbaum commented on my-video-room/module/security/templates/class-securitybuttons.php
> +		if ( $site_override ) {
asked Alex to do quick

2021-05-18 11:45 UTC, ccfredbaum commented on my-video-room/core/class-sitedefaults.php
> +	const USER_ID_SITE_DEFAULTS = 443556987;
using it instead of user id=1 which you didnt like. (but I need a user ID as the DB match is always on user_id plus something else

Given WP can create users at lower post numbers I used a high number unlikely to ever get created. 

The safest thing to do is to use user1 which we know must exist and can never be in conflict.

2021-05-18 11:46 UTC, ccfredbaum commented on my-video-room/core/shortcode/class-uservideopreference.php
> +		$this->add_shortcode( '_choose_settings', array( $this, 'choose_settings_shortcode' ) );
yeah -I'd removed the backwards compat CC code - so this was correct for the new update. But given Justcoach will be updated I will return it to an array and fix it

2021-05-18 11:48 UTC, ccfredbaum commented on my-video-room/core/shortcode/class-uservideopreference.php
> +		$this->add_shortcode( '_choose_settings', array( $this, 'choose_settings_shortcode' ) );
also need to change this add method - as choose settings is in use by the video entity module

2021-05-18 11:49 UTC, ccfredbaum commented on my-video-room/core/class-sitedefaults.php
> +	const SHORTCODE_PREFIX       = 'mvr_';
like it - will change

2021-05-18 11:55 UTC, alecsammon commented on my-video-room/core/class-sitedefaults.php
> +	const USER_ID_SITE_DEFAULTS = 443556987;
change the database column to ``user_id` BIGINT UNSIGNED NULL,` and use `NULL` as the default.

2021-05-18 11:56 UTC, ccfredbaum commented on my-video-room/module/security/shortcode/class-securityvideopreference.php
> +		$this->add_shortcode( '_choose_security_settings', array( $this, 'choose_settings_shortcode' ) );
fixed

2021-05-18 12:24 UTC, ccfredbaum commented on my-video-room/module/security/templates/class-securitybuttons.php
> +		if ( $site_override ) {
Done

2021-05-18 12:26 UTC, ccfredbaum commented on my-video-room/core/dao/class-moduleconfig.php
> +		if ( $module_id_by_url ) {
defined as null - done

2021-05-18 12:40 UTC, ccfredbaum commented on my-video-room/module/sitevideo/class-mvrsitevideo.php
> +		$this->add_shortcode( 'sitevideoroom', array( MVRSiteVideoControllers::class, 'sitevideo_shortcode' ) );
changed by new PR

2021-05-18 12:41 UTC, ccfredbaum commented on my-video-room/css/mvr-menutab.css
> +.nav-tab-active {
which one ? Nav tab active or the one above ?

2021-05-18 12:42 UTC, ccfredbaum commented on my-video-room/module/security/templates/class-securitytemplates.php
> +			' or the group moderators have allowed. Please contact any of the group admins or moderators for assistance. ',
Alex working on it

2021-05-18 12:42 UTC, alecsammon commented on my-video-room/css/mvr-menutab.css
> +.nav-tab-active {
`.nav-tab-active`

2021-05-18 12:42 UTC, ccfredbaum commented on my-video-room/core/shortcode/class-uservideopreference.php
> +		$this->add_shortcode( '_choose_settings', array( $this, 'choose_settings_shortcode' ) );
changed

2021-05-18 14:00 UTC, alecsammon commented on my-video-room/core/dao/class-moduleconfig.php
> +		if ( ! $post_object ) {
yeah - I get how it currently works - so either it can be refactored to two functions - each returning a boolean.

Or instead of returning a hard-coded string for each state, it should instead return a string from a constant.

2021-05-18 14:18 UTC, ccfredbaum commented on my-video-room/core/dao/class-moduleconfig.php
> +		$prepared_query = $wpdb->prepare( $raw_sql );
going to change to following that phpcs likes:
		$table_name_sql = $wpdb->prefix . $table_name;
		$prepared_query = $wpdb->prepare(
			'
			SELECT 1
			FROM %d 
			LIMIT 1
		',
			$table_name_sql
		);

2021-05-18 15:59 UTC, ccfredbaum commented on my-video-room/module/security/templates/class-securitytemplates.php
> +			' or the group moderators have allowed. Please contact any of the group admins or moderators for assistance. ',
Done

2021-05-18 16:02 UTC, astroyouth commented on my-video-room/class-shortcode.php
> +			add_shortcode(
Alex on it!

2021-05-18 16:05 UTC, alecsammon commented on my-video-room/core/class-sitedefaults.php
> +		// ToDO Fred to remove before final merge.
Alec on this one!

2021-05-18 16:17 UTC, alecsammon commented on my-video-room/core/class-sitedefaults.php
> +		// ToDO Fred to remove before final merge.
https://github.com/ClubCloudTech/myvideoroom-wordpress-plugin/pull/20

2021-05-18 16:17 UTC, alecsammon commented on my-video-room/core/class-sitedefaults.php
> +	public function is_elementor_active() {
Alec on this one - and other "easy" ones.

2021-05-18 16:22 UTC, ccfredbaum commented on my-video-room/core/dao/class-moduleconfig.php
> +		$prepared_query = $wpdb->prepare( $raw_sql );
Changed SQL to statements as we've discussed today on chat. They don't generate any errors I can see in terminal as I tail the logs and run the queries. All are running through prepare functions now.

2021-05-18 16:37 UTC, ccfredbaum commented on my-video-room/core/class-sitedefaults.php
> +	const SHORTCODE_PREFIX       = 'mvr_';
changed to myvideoroom as the prefix for everything (except CC for backwards compat)

2021-05-18 16:41 UTC, astroyouth commented on my-video-room/core/class-sitedefaults.php
> +	const MODULE_CORE_DISPLAY       = 'Video Default Settings';
Alex looking

2021-05-18 16:44 UTC, alecsammon commented on my-video-room/core/class-sitedefaults.php
> +		if ( is_plugin_active( 'elementor/elementor.php' ) ) {
Alec going to play with this one :)

2021-05-18 16:49 UTC, ccfredbaum commented on my-video-room/css/mvr-menutab.css
> +.nav-tab-active {
Removed

2021-05-18 17:02 UTC, ccfredbaum commented on my-video-room/core/class-sitedefaults.php
> +	const USER_ID_SITE_DEFAULTS = 443556987;
the tables use PRIMARY KEY (`user_id`, `room_name`) - so its not letting me set to null. should we auto generate primary key instead ?

2021-05-18 17:17 UTC, astroyouth commented on my-video-room/core/class-sitedefaults.php
> +	const MODULE_CORE_DISPLAY       = 'Video Default Settings';
changed to inline and translated.

2021-05-18 17:19 UTC, astroyouth commented on my-video-room/class-shortcode.php
> +			add_shortcode(
included in latest pull req littletweaks -> fred-refactor

2021-05-18 18:15 UTC, ccfredbaum commented on my-video-room/module/security/templates/class-securitybuttons.php
> +			if ( 'nourl' === $input_type ) {
simplified it

2021-05-18 19:17 UTC, alecsammon commented on my-video-room/core/class-sitedefaults.php
> +	const USER_ID_SITE_DEFAULTS = 443556987;
ah yes - of course. hmm -will take think. 

But yes - maybe we are getting to the point where an numeric primary key is best.

2021-05-19 06:47 UTC, ccfredbaum commented on my-video-room/core/dao/class-moduleconfig.php
> +		if ( ! $post_object ) {
I think two functions is a bit much for this case as it will need also more logic in the calling function. So ok if I add constant return values of 1.2.3 and call them something consistent ?

2021-05-19 06:48 UTC, ccfredbaum commented on my-video-room/module/security/templates/class-securitytemplates.php
> +		?>
Will work with Alex this morning on teaching him how to do this, and get controller logic out of views (unless you have something for him that is higher priority).

2021-05-19 06:50 UTC, ccfredbaum commented on my-video-room/library/class-sectiontemplates.php
> +		wp_enqueue_script( 'myvideoroom-admin-tabs' );
this leads me to think - I wonder if I enqueue using admin_enqueue_scripts - but in the header - I wonder if the browser will build the children ones too. I dont see a reason why not as the scripts would have been called earlier? I will try it.

2021-05-19 06:58 UTC, alecsammon commented on my-video-room/core/dao/class-moduleconfig.php
> +		if ( ! $post_object ) {
Yup - sounds ok. 

So something like this:?

```
	const PAGE_STATUS_EXISTS     = 'page-exists';
	const PAGE_STATUS_NOT_EXISTS = 'page-not-exists';
	const PAGE_STATUS_ORPHANED   = 'page-not-exists-but-has-reference';
```

2021-05-19 06:58 UTC, alecsammon commented on my-video-room/module/security/templates/class-securitytemplates.php
> +		?>
I think this would be a really good step to take :)

2021-05-19 07:00 UTC, ccfredbaum commented on my-video-room/core/dao/class-moduleconfig.php
> +		if ( ! $post_object ) {
agreed, i'll do that as soon as I finish the database null, and primary key changes.

2021-05-19 07:02 UTC, alecsammon commented on my-video-room/library/class-sectiontemplates.php
> +		wp_enqueue_script( 'myvideoroom-admin-tabs' );
so if you look in `module/roombuilder/class-module.php` then i've done it this way:

```
public function init() {
  \add_action(
	  'wp_enqueue_scripts',
	  fn() => $this->enqueue_scripts_and_styles(),
  );
  
  \add_action(
      'admin_enqueue_scripts',
       fn() => $this->enqueue_scripts_and_styles( true ),
  );
}

private function enqueue_scripts_and_styles( bool $admin = false ) {
    $plugin_version = Factory::get_instance( Version::class )->get_plugin_version();

    \wp_enqueue_style(
        'myvideoroom-room-builder-css',
        \plugins_url( '/css/roombuilder.css', \realpath( __FILE__ ) ),
        false,
        $plugin_version,
    );

    ....
}

```

2021-05-19 07:38 UTC, ccfredbaum commented on my-video-room/core/class-sitedefaults.php
> +	const USER_ID_SITE_DEFAULTS = 443556987;
OK- as discussed on teams and after testing I suggest we set this value back to 1 - which is guaranteed to exist in by default in Wordpress (and is safe to use even if it doesn't) - and does not conflict with the real user 1 settings. The reason I don't think we should set this to null, is we type check for INT in every function that calls user ID (everywhere)- and having a user_id of null means weakening that protection which I feel is more harm than benefit. User1 is already protected in the room namespace so there can be no conflict (as site default settings have a different room name). The databases have been amended as suggested to primary keys that auto increment, and I've added back in the mandatory user_id setting to NOT NULL.  Please let me know if you agree and I will resolve this conversation, alternatively we can leave open and discuss on a call.

2021-05-19 07:41 UTC, alecsammon commented on my-video-room/core/class-sitedefaults.php
> +	const USER_ID_SITE_DEFAULTS = 443556987;
So I don't agree - my reasons for suggesting that we didn't use 1 in the first place still stand.

2021-05-19 07:44 UTC, ccfredbaum commented on my-video-room/core/class-sitedefaults.php
> +	const USER_ID_SITE_DEFAULTS = 443556987;
remind me what the objection was to using 1 ?

2021-05-19 07:50 UTC, ccfredbaum commented on my-video-room/core/class-sitedefaults.php
> +	const USER_ID_SITE_DEFAULTS = 443556987;
OK - what if we remove UNSIGNED - and set the constant to  UserID =  -1    which won't conflict - but still is an integer ?

2021-05-19 07:55 UTC, alecsammon commented on my-video-room/core/class-sitedefaults.php
> +	const USER_ID_SITE_DEFAULTS = 443556987;
In regards to the `-1`- YES! this would be a good solution!

It would also mean the id column would match the type of the `wp_users` table - allow us to do stuff with data integrity in the future.

However - mid-term I would still recommend that the majority of the code base uses `null`, it's a limitation on the database that we have to use -1. But this could be a future enhacement.

2021-05-19 07:57 UTC, ccfredbaum commented on my-video-room/core/class-sitedefaults.php
> +	const USER_ID_SITE_DEFAULTS = 443556987;
Cool- so updated to -1 - and tested - and all settings work

2021-05-19 08:19 UTC, ccfredbaum commented on my-video-room/core/dao/class-moduleconfig.php
> +		if ( ! $post_object ) {
Done

2021-05-19 18:48 UTC, ccfredbaum commented on my-video-room/views/shortcode/view-shortcode-uservideopreference.php
> +				$reception_enabled = Factory::get_instance( UserVideoPreferenceDAO::class )->read_user_video_settings( $user_id, $room_name, 'reception_enabled' );
will update as discussed over the next 12 hours

2021-05-24 16:33 UTC, alecsammon commented on my-video-room/class-shortcode.php
> +		$shortcode_prefixes = SiteDefaults::SHORTCODE_PREFIXES;
Do we still need the array of prefixes? Would prefer that we don't release this bit.

2021-05-24 16:33 UTC, alecsammon commented on my-video-room/class-sitedefaults.php
> +	const SHORTCODE_PREFIXES     = array( 'cc', 'myvideoroom_' );
see comment before re. array of prefixes - I don't think we should release with `cc`

2021-05-24 16:36 UTC, ccfredbaum commented on my-video-room/class-sitedefaults.php
> +	const SHORTCODE_PREFIXES     = array( 'cc', 'myvideoroom_' );
lets kill it

2021-05-25 09:15 UTC, alecsammon commented on my-video-room/dao/class-moduleconfig.php
> +	public function module_activation_button( int $module_id ): string {
This function needs to be moved out of the DAO. I guess to the controller layer

2021-05-28 05:13 UTC, alecsammon commented
Manually merged

2021-05-28 05:13 UTC, closed without merging