Littletweaks
ClubCloudTech/myvideoroom-wordpress-plugin pull request #24
Opened 2021-05-18 17:18 UTC by astroyouth

some tweaks from the main PR coments.

2021-05-18 18:14 UTC, ccfredbaum commented
not sure about the shortcode change as we are still rendering CC as a backup for JustCoach

2021-05-18 19:56 UTC, alecsammon commented on my-video-room/core/class-sitedefaults.php
> +		$name = self::esc_html_e( 'Video Default Settings', 'my-video-room' );
this is wrong!

`$name = esc_html__( 'Video Default Settings', 'my-video-room' );`

2021-05-18 19:57 UTC, alecsammon commented on my-video-room/module/security/templates/class-securitybuttons.php
> +				$output .= '<a class="button button-primary" style="background-color:#daab33">' . esc_html_e( 'Site Enforcement Active', 'my-video-room' ) . '</a>';
as these ones are in a php string then they should not be echo'ed so you need to use `esc_html__` and not `esc_html_e`.

This is throughout this file.

2021-05-18 19:58 UTC, alecsammon requested changes
Please see inline comments

2021-05-18 20:03 UTC, astroyouth commented on my-video-room/module/security/templates/class-securitybuttons.php
> +				$output .= '<a class="button button-primary" style="background-color:#daab33">' . esc_html_e( 'Site Enforcement Active', 'my-video-room' ) . '</a>';
corrected. 
waiting for a couple of other changes for push and PR

2021-05-18 20:08 UTC, astroyouth commented
changes done.

2021-05-18 20:08 UTC, alecsammon commented on my-video-room/core/class-sitedefaults.php
> +		$name = self::esc_html__( 'Video Default Settings', 'my-video-room' );
this is still wrong. you need to remove the `self::`

2021-05-18 20:11 UTC, alecsammon approved these changes

2021-05-19 07:23 UTC, alecsammon commented
@astroyouth  - something has gone weird with this. Did you merge Fred's branch into it?

2021-05-19 07:24 UTC, astroyouth commented
Only did pull requests I wouldn't dare do a merge.

2021-05-19 07:26 UTC, alecsammon commented
Ok - I will take a look


On Wed, 19 May 2021 at 08:25, Alex Dale ***@***.***> wrote:

> Only did pull requests I wouldn't dare do a merge.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/ClubCloudTech/myvideoroom-wordpress-plugin/pull/24#issuecomment-843821847>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AACKL7GYEJIU3XQGJNGWWQLTONRVJANCNFSM45C6EHIQ>
> .
>

2021-05-19 07:40 UTC, astroyouth commented
Willco.

2021-05-19 11:52 UTC, alecsammon commented
Most of these have already been merged - I've taken the remaining ones onto a new branch.

2021-05-19 11:52 UTC, closed without merging